masonegger:
  name: Mason Egger
  description: Developer, Educator, Community Organizer
  avatar: https://github.com/masonegger.png
josh-schneider:
  name: Josh Schneider
  description: Test Automation architect at Dell Technologies. Geeky dad with 1+ years in Improv comedy training and performing.
  avatar: https://www.gravatar.com/avatar/4fd8d11f5cc00e1fa20dc9a596b16088
